### Successful login
POST https://flask-lab-iman123.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "correct_password"
}

### Failed login #1
POST https://flask-lab-iman123.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrong1"
}

### Failed login #2
POST https://flask-lab-iman123.azurewebsites.net/login
Content-Type: application/json

{
  "username": "admin",
  "password": "wrong2"
}
